name: Deploy FR Tools Beta

on:
  push:
    branches:
      - development

permissions:
  contents: read

jobs:
  beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Beta
        run: node build/build.js

      - name: Prepare Beta Deploy
        run: |
          mkdir beta-deploy
          cp dist/FRTools.user.js beta-deploy/
          cp dist/FRTools.meta.js beta-deploy/

      - name: Deploy Beta Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USER }}
          key: ${{ secrets.BETA_KEY }}
          source: "beta-deploy/*"
          target: /var/www/frtools-beta